server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/syso?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    user:
      name: test
      password: 1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: "ohohgeunhy@gmail.com"
    password: "********"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true






